version: 2

updates:
  # Enable version updates for uv lockfiles
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "nkbud"
    labels:
      - "dependencies"
      - "security"
    # Group all minor and patch updates into a single PR
    groups:
      production:
        patterns:
          - "*"
        exclude-patterns:
          - "black"
          - "ruff"
          - "isort"
          - "pytest*"
        update-types:
          - "minor"
          - "patch"
      dev-tools:
        patterns:
          - "black"
          - "ruff"
          - "isort"
          - "pytest*"
        update-types:
          - "minor"
          - "patch"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    reviewers:
      - "nkbud"
    labels:
      - "dependencies"
      - "github-actions"
    # Auto-merge security patches
    open-pull-requests-limit: 5